-- ==========================================================
-- NEXUS POS & INVENTORY MANAGEMENT SYSTEM - SUPABASE SCHEMA
-- Run this script in your Supabase Project's SQL Editor
-- ==========================================================

-- 1. DEPARTMENTS TABLE
CREATE TABLE IF NOT EXISTS public.departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    code TEXT NOT NULL UNIQUE,
    description TEXT,
    color TEXT DEFAULT '#4f46e5',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode TEXT NOT NULL UNIQUE,
    sku TEXT,
    name TEXT NOT NULL,
    department_id BIGINT NOT NULL REFERENCES public.departments(id) ON DELETE RESTRICT,
    price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    cost_price NUMERIC(10, 2) DEFAULT 0.00,
    stock_quantity INTEGER NOT NULL DEFAULT 0,
    min_stock_level INTEGER NOT NULL DEFAULT 5,
    unit TEXT DEFAULT 'pcs',
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. SALES TABLE
CREATE TABLE IF NOT EXISTS public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_number TEXT NOT NULL UNIQUE,
    subtotal NUMERIC(10, 2) NOT NULL,
    tax_rate NUMERIC(5, 2) DEFAULT 0.00,
    tax_amount NUMERIC(10, 2) DEFAULT 0.00,
    discount NUMERIC(10, 2) DEFAULT 0.00,
    total NUMERIC(10, 2) NOT NULL,
    payment_method TEXT NOT NULL DEFAULT 'CASH', -- 'CASH', 'CARD', 'UPI_QR', 'SPLIT'
    amount_paid NUMERIC(10, 2) NOT NULL,
    change_due NUMERIC(10, 2) DEFAULT 0.00,
    customer_name TEXT DEFAULT 'Walk-in Customer',
    customer_phone TEXT,
    status TEXT DEFAULT 'COMPLETED',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. SALE ITEMS TABLE
CREATE TABLE IF NOT EXISTS public.sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL REFERENCES public.sales(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    product_name TEXT NOT NULL,
    barcode TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(10, 2) NOT NULL,
    total_price NUMERIC(10, 2) NOT NULL
);

-- 5. STOCK MOVEMENTS (AUDIT TRAIL)
CREATE TABLE IF NOT EXISTS public.stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    type TEXT NOT NULL, -- 'INITIAL', 'RESTOCK', 'SALE', 'ADJUSTMENT_ADD', 'ADJUSTMENT_REMOVE', 'RETURN'
    quantity_change INTEGER NOT NULL,
    quantity_before INTEGER NOT NULL,
    quantity_after INTEGER NOT NULL,
    reference_id TEXT,
    reason TEXT,
    customer_name TEXT,
    customer_phone TEXT,
    payment_method TEXT,
    sale_id BIGINT REFERENCES public.sales(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- INDICES FOR PERFORMANCE
CREATE INDEX IF NOT EXISTS idx_products_barcode ON public.products(barcode);
CREATE INDEX IF NOT EXISTS idx_products_dept ON public.products(department_id);
CREATE INDEX IF NOT EXISTS idx_movements_prod ON public.stock_movements(product_id);
CREATE INDEX IF NOT EXISTS idx_movements_created ON public.stock_movements(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sales_created ON public.sales(created_at DESC);

-- ENABLE ROW LEVEL SECURITY (RLS)
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY;

-- ALLOW PUBLIC / ANON ACCESS FOR DEMO & EASY SHARING
CREATE POLICY "Allow public all access on departments" ON public.departments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public all access on products" ON public.products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public all access on sales" ON public.sales FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public all access on sale_items" ON public.sale_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public all access on stock_movements" ON public.stock_movements FOR ALL USING (true) WITH CHECK (true);

-- ENABLE REALTIME FOR LIVE COLLABORATION ACROSS DEVICES
ALTER PUBLICATION supabase_realtime ADD TABLE public.products;
ALTER PUBLICATION supabase_realtime ADD TABLE public.stock_movements;
ALTER PUBLICATION supabase_realtime ADD TABLE public.sales;

-- 6. ATOMIC POS CHECKOUT RPC FUNCTION
CREATE OR REPLACE FUNCTION public.process_pos_checkout(
    p_items JSONB,
    p_subtotal NUMERIC,
    p_tax_rate NUMERIC,
    p_tax_amount NUMERIC,
    p_discount NUMERIC,
    p_total NUMERIC,
    p_payment_method TEXT,
    p_amount_paid NUMERIC,
    p_change_due NUMERIC,
    p_customer_name TEXT,
    p_customer_phone TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_receipt_number TEXT;
    v_sale_id BIGINT;
    v_item JSONB;
    v_prod RECORD;
    v_qty INT;
    v_unit_price NUMERIC;
    v_total_price NUMERIC;
    v_qty_before INT;
    v_qty_after INT;
    v_date_str TEXT;
    v_rand_suffix TEXT;
    v_res_items JSONB := '[]'::JSONB;
BEGIN
    -- Generate receipt number e.g. REC-20260909-XXXX
    v_date_str := to_char(timezone('utc', now()), 'YYYYMMDD');
    v_rand_suffix := upper(substr(md5(random()::text), 1, 4));
    v_receipt_number := 'REC-' || v_date_str || '-' || v_rand_suffix;

    -- 1. Insert into sales
    INSERT INTO public.sales (
        receipt_number, subtotal, tax_rate, tax_amount, discount, total,
        payment_method, amount_paid, change_due, customer_name, customer_phone
    ) VALUES (
        v_receipt_number, p_subtotal, p_tax_rate, p_tax_amount, p_discount, p_total,
        p_payment_method, p_amount_paid, p_change_due, COALESCE(p_customer_name, 'Walk-in Customer'), p_customer_phone
    ) RETURNING id INTO v_sale_id;

    -- 2. Process each item
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        v_qty := (v_item->>'quantity')::INT;
        
        -- Lock product row
        SELECT * INTO v_prod FROM public.products 
        WHERE id = (v_item->>'product_id')::BIGINT 
           OR barcode = (v_item->>'barcode')::TEXT
        FOR UPDATE;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'Product not found: %', COALESCE(v_item->>'barcode', v_item->>'product_id');
        END IF;

        IF v_prod.stock_quantity < v_qty THEN
            RAISE EXCEPTION 'Insufficient stock for "%". Available: %, Requested: %', v_prod.name, v_prod.stock_quantity, v_qty;
        END IF;

        v_unit_price := COALESCE((v_item->>'unit_price')::NUMERIC, v_prod.price);
        v_total_price := round(v_unit_price * v_qty, 2);
        v_qty_before := v_prod.stock_quantity;
        v_qty_after := v_qty_before - v_qty;

        -- Update stock
        UPDATE public.products 
        SET stock_quantity = v_qty_after, updated_at = timezone('utc', now())
        WHERE id = v_prod.id;

        -- Insert sale item
        INSERT INTO public.sale_items (
            sale_id, product_id, product_name, barcode, quantity, unit_price, total_price
        ) VALUES (
            v_sale_id, v_prod.id, v_prod.name, v_prod.barcode, v_qty, v_unit_price, v_total_price
        );

        -- Record movement history
        INSERT INTO public.stock_movements (
            product_id, type, quantity_change, quantity_before, quantity_after,
            reference_id, reason, customer_name, customer_phone, payment_method, sale_id
        ) VALUES (
            v_prod.id, 'SALE', -v_qty, v_qty_before, v_qty_after,
            v_receipt_number, 'POS Sale #' || v_receipt_number,
            COALESCE(p_customer_name, 'Walk-in Customer'), p_customer_phone, p_payment_method, v_sale_id
        );

        v_res_items := v_res_items || jsonb_build_object(
            'product_id', v_prod.id,
            'name', v_prod.name,
            'barcode', v_prod.barcode,
            'quantity', v_qty,
            'unit_price', v_unit_price,
            'total_price', v_total_price,
            'unit', v_prod.unit
        );
    END LOOP;

    RETURN jsonb_build_object(
        'id', v_sale_id,
        'receipt_number', v_receipt_number,
        'subtotal', p_subtotal,
        'tax_rate', p_tax_rate,
        'tax_amount', p_tax_amount,
        'discount', p_discount,
        'total', p_total,
        'payment_method', p_payment_method,
        'amount_paid', p_amount_paid,
        'change_due', p_change_due,
        'customer_name', COALESCE(p_customer_name, 'Walk-in Customer'),
        'created_at', timezone('utc', now()),
        'items', v_res_items
    );
END;
$$;

-- 7. SEED INITIAL DEPARTMENTS & PRODUCTS IF EMPTY
DO $$
DECLARE
    v_dept_count INT;
    v_bev_id BIGINT;
    v_groc_id BIGINT;
    v_dairy_id BIGINT;
    v_bake_id BIGINT;
    v_care_id BIGINT;
    v_elec_id BIGINT;
BEGIN
    SELECT count(*) INTO v_dept_count FROM public.departments;
    IF v_dept_count = 0 THEN
        INSERT INTO public.departments (name, code, description, color) VALUES 
        ('Beverages', 'BEV', 'Soft drinks, juices, water, energy drinks', '#0ea5e9') RETURNING id INTO v_bev_id;
        
        INSERT INTO public.departments (name, code, description, color) VALUES 
        ('Grocery & Pantry', 'GROC', 'Flour, rice, spices, canned foods', '#10b981') RETURNING id INTO v_groc_id;
        
        INSERT INTO public.departments (name, code, description, color) VALUES 
        ('Dairy & Frozen', 'DAIRY', 'Milk, cheese, butter, ice cream', '#6366f1') RETURNING id INTO v_dairy_id;
        
        INSERT INTO public.departments (name, code, description, color) VALUES 
        ('Bakery & Snacks', 'BAKE', 'Breads, cookies, chips, crackers', '#f59e0b') RETURNING id INTO v_bake_id;
        
        INSERT INTO public.departments (name, code, description, color) VALUES 
        ('Personal Care', 'CARE', 'Soap, shampoo, hygiene, cosmetics', '#ec4899') RETURNING id INTO v_care_id;
        
        INSERT INTO public.departments (name, code, description, color) VALUES 
        ('Electronics & Tech', 'ELEC', 'Cables, chargers, earphones, accessories', '#8b5cf6') RETURNING id INTO v_elec_id;
    END IF;
END;
$$;
