import type { Pool } from 'pg';

/**
 * Versioned, forward-only Postgres migrations, tracked in schema_migrations.
 * Each migration runs in its own transaction under an advisory lock so two
 * server instances starting together cannot both apply it. Never edit a
 * migration that has shipped; add a new one.
 *
 * Migration 1 recreates the layout the old supabase_schema.sql produced, so a
 * database that already has those tables passes through it untouched and is
 * then upgraded by 2..4 exactly like a fresh one.
 */
interface Migration {
  version: number;
  name: string;
  sql: string;
}

const migrations: Migration[] = [
  {
    version: 1,
    name: 'baseline',
    sql: `
      CREATE TABLE IF NOT EXISTS departments (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name        TEXT NOT NULL UNIQUE,
        code        TEXT NOT NULL UNIQUE,
        description TEXT,
        color       TEXT DEFAULT '#4f46e5',
        created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
      );

      CREATE TABLE IF NOT EXISTS products (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        barcode         TEXT NOT NULL UNIQUE,
        sku             TEXT,
        name            TEXT NOT NULL,
        department_id   BIGINT NOT NULL REFERENCES departments(id) ON DELETE RESTRICT,
        price           NUMERIC(10, 2) NOT NULL DEFAULT 0,
        cost_price      NUMERIC(10, 2) DEFAULT 0,
        stock_quantity  INTEGER NOT NULL DEFAULT 0,
        min_stock_level INTEGER NOT NULL DEFAULT 5,
        unit            TEXT DEFAULT 'pcs',
        image_url       TEXT,
        created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
      );

      CREATE TABLE IF NOT EXISTS sales (
        id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        receipt_number TEXT NOT NULL UNIQUE,
        subtotal       NUMERIC(10, 2) NOT NULL,
        tax_rate       NUMERIC(5, 2) DEFAULT 0,
        tax_amount     NUMERIC(10, 2) DEFAULT 0,
        discount       NUMERIC(10, 2) DEFAULT 0,
        total          NUMERIC(10, 2) NOT NULL,
        payment_method TEXT NOT NULL DEFAULT 'CASH',
        amount_paid    NUMERIC(10, 2) NOT NULL,
        change_due     NUMERIC(10, 2) DEFAULT 0,
        customer_name  TEXT DEFAULT 'Walk-in Customer',
        customer_phone TEXT,
        status         TEXT DEFAULT 'COMPLETED',
        created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
      );

      CREATE TABLE IF NOT EXISTS sale_items (
        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sale_id      BIGINT NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
        product_id   BIGINT REFERENCES products(id) ON DELETE SET NULL,
        product_name TEXT NOT NULL,
        barcode      TEXT NOT NULL,
        quantity     INTEGER NOT NULL,
        unit_price   NUMERIC(10, 2) NOT NULL,
        total_price  NUMERIC(10, 2) NOT NULL
      );

      CREATE TABLE IF NOT EXISTS stock_movements (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        product_id      BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
        type            TEXT NOT NULL,
        quantity_change INTEGER NOT NULL,
        quantity_before INTEGER NOT NULL,
        quantity_after  INTEGER NOT NULL,
        reference_id    TEXT,
        reason          TEXT,
        created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
      );

      ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS customer_name  TEXT;
      ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS customer_phone TEXT;
      ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS payment_method TEXT;
      ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS sale_id BIGINT REFERENCES sales(id) ON DELETE SET NULL;

      CREATE INDEX IF NOT EXISTS idx_products_barcode  ON products(barcode);
      CREATE INDEX IF NOT EXISTS idx_products_dept     ON products(department_id);
      CREATE INDEX IF NOT EXISTS idx_movements_prod    ON stock_movements(product_id);
      CREATE INDEX IF NOT EXISTS idx_movements_created ON stock_movements(created_at DESC);
      CREATE INDEX IF NOT EXISTS idx_sales_created     ON sales(created_at DESC);
    `,
  },
  {
    version: 2,
    name: 'money_in_integer_cents',
    sql: `
      -- The browser used to call this to check out; the Express server owns checkout now.
      DROP FUNCTION IF EXISTS process_pos_checkout;

      ALTER TABLE products
        ADD COLUMN IF NOT EXISTS price_cents      BIGINT NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS cost_price_cents BIGINT NOT NULL DEFAULT 0;
      UPDATE products SET
        price_cents      = ROUND(price * 100)::BIGINT,
        cost_price_cents = ROUND(COALESCE(cost_price, 0) * 100)::BIGINT;
      ALTER TABLE products DROP COLUMN IF EXISTS price, DROP COLUMN IF EXISTS cost_price;

      ALTER TABLE sales
        ADD COLUMN IF NOT EXISTS subtotal_cents    BIGINT NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS tax_rate_bps      INTEGER NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS tax_cents         BIGINT NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS discount_cents    BIGINT NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS total_cents       BIGINT NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS amount_paid_cents BIGINT NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS change_due_cents  BIGINT NOT NULL DEFAULT 0;
      UPDATE sales SET
        subtotal_cents    = ROUND(subtotal * 100)::BIGINT,
        tax_rate_bps      = ROUND(COALESCE(tax_rate, 0) * 100)::INTEGER,
        tax_cents         = ROUND(COALESCE(tax_amount, 0) * 100)::BIGINT,
        discount_cents    = ROUND(COALESCE(discount, 0) * 100)::BIGINT,
        total_cents       = ROUND(total * 100)::BIGINT,
        amount_paid_cents = ROUND(amount_paid * 100)::BIGINT,
        change_due_cents  = ROUND(COALESCE(change_due, 0) * 100)::BIGINT;
      ALTER TABLE sales
        DROP COLUMN IF EXISTS subtotal, DROP COLUMN IF EXISTS tax_rate, DROP COLUMN IF EXISTS tax_amount,
        DROP COLUMN IF EXISTS discount, DROP COLUMN IF EXISTS total, DROP COLUMN IF EXISTS amount_paid,
        DROP COLUMN IF EXISTS change_due;
      ALTER TABLE sales ALTER COLUMN status SET NOT NULL;

      ALTER TABLE sale_items
        ADD COLUMN IF NOT EXISTS unit_price_cents  BIGINT NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS total_price_cents BIGINT NOT NULL DEFAULT 0;
      UPDATE sale_items SET
        unit_price_cents  = ROUND(unit_price * 100)::BIGINT,
        total_price_cents = ROUND(total_price * 100)::BIGINT;
      ALTER TABLE sale_items DROP COLUMN IF EXISTS unit_price, DROP COLUMN IF EXISTS total_price;

      -- Receipts are history: refuse to delete a product that appears on one.
      ALTER TABLE sale_items DROP CONSTRAINT IF EXISTS sale_items_product_id_fkey;
      ALTER TABLE sale_items
        ADD CONSTRAINT sale_items_product_id_fkey
        FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT;

      CREATE INDEX IF NOT EXISTS idx_sale_items_sale ON sale_items(sale_id);
    `,
  },
  {
    version: 3,
    name: 'settings_and_sequences',
    sql: `
      CREATE TABLE IF NOT EXISTS settings (
        key        TEXT PRIMARY KEY,
        value      TEXT NOT NULL,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      INSERT INTO settings (key, value) VALUES
        ('store_name', 'Nexus POS'),
        ('currency', 'USD'),
        ('tax_rate_bps', '500')
      ON CONFLICT (key) DO NOTHING;

      CREATE TABLE IF NOT EXISTS sequences (
        name  TEXT PRIMARY KEY,
        value BIGINT NOT NULL DEFAULT 0
      );
    `,
  },
  {
    version: 4,
    name: 'lock_down_public_access',
    sql: `
      -- The old setup let the browser's anon key read and write every table.
      -- The Express server connects as the owner role, which bypasses RLS, so
      -- enabling RLS with no policies shuts the anon/authenticated roles out.
      ALTER TABLE departments     ENABLE ROW LEVEL SECURITY;
      ALTER TABLE products        ENABLE ROW LEVEL SECURITY;
      ALTER TABLE sales           ENABLE ROW LEVEL SECURITY;
      ALTER TABLE sale_items      ENABLE ROW LEVEL SECURITY;
      ALTER TABLE stock_movements ENABLE ROW LEVEL SECURITY;
      ALTER TABLE settings        ENABLE ROW LEVEL SECURITY;
      ALTER TABLE sequences       ENABLE ROW LEVEL SECURITY;

      DROP POLICY IF EXISTS "Allow public all access on departments"     ON departments;
      DROP POLICY IF EXISTS "Allow public all access on products"        ON products;
      DROP POLICY IF EXISTS "Allow public all access on sales"           ON sales;
      DROP POLICY IF EXISTS "Allow public all access on sale_items"      ON sale_items;
      DROP POLICY IF EXISTS "Allow public all access on stock_movements" ON stock_movements;

      -- Stop broadcasting table changes to anonymous realtime subscribers.
      DO $$
      DECLARE t TEXT;
      BEGIN
        IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
          FOR t IN
            SELECT tablename FROM pg_publication_tables
            WHERE pubname = 'supabase_realtime' AND schemaname = current_schema()
              AND tablename IN ('products', 'stock_movements', 'sales')
          LOOP
            EXECUTE format('ALTER PUBLICATION supabase_realtime DROP TABLE %I', t);
          END LOOP;
        END IF;
      END $$;
    `,
  },
  {
    version: 5,
    name: 'users_sessions_and_actors',
    sql: `
      CREATE TABLE IF NOT EXISTS users (
        id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username      TEXT NOT NULL UNIQUE,
        display_name  TEXT NOT NULL,
        password_hash TEXT NOT NULL,
        role          TEXT NOT NULL CHECK (role IN ('OWNER', 'MANAGER', 'CASHIER')),
        is_active     BOOLEAN NOT NULL DEFAULT true,
        created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
        last_login_at TIMESTAMPTZ
      );

      CREATE TABLE IF NOT EXISTS sessions (
        id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        token_hash TEXT NOT NULL UNIQUE,
        user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        expires_at TIMESTAMPTZ NOT NULL,
        revoked_at TIMESTAMPTZ,
        ip         TEXT
      );
      CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);

      -- Who did it: the cashier on every sale, the user on every stock movement.
      ALTER TABLE sales           ADD COLUMN IF NOT EXISTS cashier_id BIGINT REFERENCES users(id) ON DELETE SET NULL;
      ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS user_id    BIGINT REFERENCES users(id) ON DELETE SET NULL;

      ALTER TABLE users    ENABLE ROW LEVEL SECURITY;
      ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
    `,
  },
  {
    version: 6,
    name: 'returns_and_voids',
    sql: `
      CREATE TABLE IF NOT EXISTS returns (
        id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        return_number TEXT NOT NULL UNIQUE,
        sale_id       BIGINT NOT NULL REFERENCES sales(id) ON DELETE RESTRICT,
        kind          TEXT NOT NULL DEFAULT 'RETURN' CHECK (kind IN ('RETURN', 'VOID')),
        refund_cents  BIGINT NOT NULL,
        refund_method TEXT NOT NULL,
        reason        TEXT,
        processed_by  BIGINT REFERENCES users(id) ON DELETE SET NULL,
        created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE INDEX IF NOT EXISTS idx_returns_sale ON returns(sale_id);

      CREATE TABLE IF NOT EXISTS return_items (
        id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        return_id        BIGINT NOT NULL REFERENCES returns(id) ON DELETE CASCADE,
        sale_item_id     BIGINT NOT NULL REFERENCES sale_items(id) ON DELETE RESTRICT,
        product_id       BIGINT REFERENCES products(id) ON DELETE RESTRICT,
        product_name     TEXT NOT NULL,
        quantity         INTEGER NOT NULL CHECK (quantity > 0),
        unit_price_cents BIGINT NOT NULL,
        refund_cents     BIGINT NOT NULL,
        restock          BOOLEAN NOT NULL DEFAULT true,
        condition        TEXT
      );
      CREATE INDEX IF NOT EXISTS idx_return_items_sale_item ON return_items(sale_item_id);

      INSERT INTO settings (key, value) VALUES
        ('return_window_days', '30'),
        ('refund_approval_threshold_cents', '5000')
      ON CONFLICT (key) DO NOTHING;

      ALTER TABLE returns      ENABLE ROW LEVEL SECURITY;
      ALTER TABLE return_items ENABLE ROW LEVEL SECURITY;
    `,
  },
  {
    version: 7,
    name: 'barcode_lookup_cache',
    sql: `
      -- Answers from the external product registries, so a barcode is fetched
      -- once and never again. Misses are cached too, with a shorter life, so a
      -- shop full of unlisted stock does not re-query the registries on every scan.
      CREATE TABLE IF NOT EXISTS barcode_lookups (
        barcode      TEXT PRIMARY KEY,
        found        BOOLEAN NOT NULL,
        name         TEXT,
        brand        TEXT,
        unit         TEXT,
        category     TEXT,
        source       TEXT,
        looked_up_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE INDEX IF NOT EXISTS idx_barcode_lookups_looked_up ON barcode_lookups(looked_up_at);

      ALTER TABLE barcode_lookups ENABLE ROW LEVEL SECURITY;
    `,
  },
  {
    version: 8,
    name: 'archive_products',
    sql: `
      -- A product that has been sold can never be deleted: sale_items.product_id
      -- is ON DELETE RESTRICT, which is what stops a receipt line pointing at
      -- nothing. Archiving is the way to retire such a product — it leaves the
      -- catalogue and the register but keeps every receipt it appears on intact.
      -- Staff already work this way (users.is_active); products now match.
      ALTER TABLE products ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;

      -- Almost every read wants the active catalogue only.
      CREATE INDEX IF NOT EXISTS idx_products_active ON products(is_active) WHERE is_active;
    `,
  },
  {
    version: 9,
    name: 'multi_tenant',
    sql: `
      -- ================================================================
      -- One database, many sellers. Every seller ("tenant") sees only its
      -- own rows, enforced by the database rather than by remembering a
      -- WHERE clause: row-level security is FORCED on every scoped table,
      -- so even the owning role is bound by the policy. A transaction
      -- declares its tenant with set_config('app.tenant_id', ..., true),
      -- which Postgres discards at COMMIT or ROLLBACK — nothing can leak
      -- through a pooled connection. A transaction that declares nothing
      -- sees nothing.
      --
      -- The shop that existed before this migration becomes tenant 1.
      -- ================================================================

      CREATE TABLE IF NOT EXISTS tenants (
        id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        slug           TEXT NOT NULL UNIQUE,
        name           TEXT NOT NULL,
        is_active      BOOLEAN NOT NULL DEFAULT true,
        created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
        deactivated_at TIMESTAMPTZ
      );

      INSERT INTO tenants (id, slug, name)
      SELECT 1, 'default', COALESCE((SELECT value FROM settings WHERE key = 'store_name'), 'Default Store')
      WHERE NOT EXISTS (SELECT 1 FROM tenants WHERE id = 1);
      SELECT setval(pg_get_serial_sequence('tenants', 'id'), GREATEST((SELECT MAX(id) FROM tenants), 1));

      -- Platform administrators are not tenant users. They live apart so the
      -- per-shop role hierarchy (OWNER > MANAGER > CASHIER) and its invariants
      -- stay untouched.
      CREATE TABLE IF NOT EXISTS platform_admins (
        id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username      TEXT NOT NULL UNIQUE,
        display_name  TEXT NOT NULL,
        password_hash TEXT NOT NULL,
        is_active     BOOLEAN NOT NULL DEFAULT true,
        created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
        last_login_at TIMESTAMPTZ
      );

      -- acting_tenant_id set = this admin is currently "switched into" that
      -- seller. Money operations refuse such sessions; see lib/authz.ts.
      CREATE TABLE IF NOT EXISTS admin_sessions (
        id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        admin_id         BIGINT NOT NULL REFERENCES platform_admins(id) ON DELETE CASCADE,
        token_hash       TEXT NOT NULL UNIQUE,
        acting_tenant_id BIGINT REFERENCES tenants(id),
        created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
        expires_at       TIMESTAMPTZ NOT NULL,
        revoked_at       TIMESTAMPTZ,
        ip               TEXT
      );
      CREATE INDEX IF NOT EXISTS idx_admin_sessions_admin ON admin_sessions(admin_id);

      -- Everything an admin does, including every write made while switched
      -- into a seller. This is the audit trail the seller can be shown.
      CREATE TABLE IF NOT EXISTS admin_actions (
        id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        admin_id   BIGINT NOT NULL REFERENCES platform_admins(id),
        action     TEXT NOT NULL,
        tenant_id  BIGINT REFERENCES tenants(id),
        details    JSONB,
        ip         TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE INDEX IF NOT EXISTS idx_admin_actions_tenant ON admin_actions(tenant_id, created_at DESC);

      -- ---- tenant_id on every scoped table, backfilled to the existing shop ----
      ALTER TABLE users           ADD COLUMN IF NOT EXISTS tenant_id BIGINT REFERENCES tenants(id);
      ALTER TABLE sessions        ADD COLUMN IF NOT EXISTS tenant_id BIGINT REFERENCES tenants(id);
      ALTER TABLE departments     ADD COLUMN IF NOT EXISTS tenant_id BIGINT REFERENCES tenants(id);
      ALTER TABLE products        ADD COLUMN IF NOT EXISTS tenant_id BIGINT REFERENCES tenants(id);
      ALTER TABLE sales           ADD COLUMN IF NOT EXISTS tenant_id BIGINT REFERENCES tenants(id);
      ALTER TABLE sale_items      ADD COLUMN IF NOT EXISTS tenant_id BIGINT REFERENCES tenants(id);
      ALTER TABLE returns         ADD COLUMN IF NOT EXISTS tenant_id BIGINT REFERENCES tenants(id);
      ALTER TABLE return_items    ADD COLUMN IF NOT EXISTS tenant_id BIGINT REFERENCES tenants(id);
      ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS tenant_id BIGINT REFERENCES tenants(id);
      ALTER TABLE settings        ADD COLUMN IF NOT EXISTS tenant_id BIGINT REFERENCES tenants(id);
      ALTER TABLE sequences       ADD COLUMN IF NOT EXISTS tenant_id BIGINT REFERENCES tenants(id);

      UPDATE users           SET tenant_id = 1 WHERE tenant_id IS NULL;
      UPDATE sessions        SET tenant_id = 1 WHERE tenant_id IS NULL;
      UPDATE departments     SET tenant_id = 1 WHERE tenant_id IS NULL;
      UPDATE products        SET tenant_id = 1 WHERE tenant_id IS NULL;
      UPDATE sales           SET tenant_id = 1 WHERE tenant_id IS NULL;
      UPDATE sale_items      SET tenant_id = 1 WHERE tenant_id IS NULL;
      UPDATE returns         SET tenant_id = 1 WHERE tenant_id IS NULL;
      UPDATE return_items    SET tenant_id = 1 WHERE tenant_id IS NULL;
      UPDATE stock_movements SET tenant_id = 1 WHERE tenant_id IS NULL;
      UPDATE settings        SET tenant_id = 1 WHERE tenant_id IS NULL;
      UPDATE sequences       SET tenant_id = 1 WHERE tenant_id IS NULL;

      ALTER TABLE users           ALTER COLUMN tenant_id SET NOT NULL;
      ALTER TABLE sessions        ALTER COLUMN tenant_id SET NOT NULL;
      ALTER TABLE departments     ALTER COLUMN tenant_id SET NOT NULL;
      ALTER TABLE products        ALTER COLUMN tenant_id SET NOT NULL;
      ALTER TABLE sales           ALTER COLUMN tenant_id SET NOT NULL;
      ALTER TABLE sale_items      ALTER COLUMN tenant_id SET NOT NULL;
      ALTER TABLE returns         ALTER COLUMN tenant_id SET NOT NULL;
      ALTER TABLE return_items    ALTER COLUMN tenant_id SET NOT NULL;
      ALTER TABLE stock_movements ALTER COLUMN tenant_id SET NOT NULL;
      ALTER TABLE settings        ALTER COLUMN tenant_id SET NOT NULL;
      ALTER TABLE sequences       ALTER COLUMN tenant_id SET NOT NULL;

      -- ---- uniqueness becomes per-tenant: two shops may both have a "BEV" ----
      ALTER TABLE users       DROP CONSTRAINT IF EXISTS users_username_key;
      ALTER TABLE users       ADD CONSTRAINT users_tenant_username_key UNIQUE (tenant_id, username);
      ALTER TABLE departments DROP CONSTRAINT IF EXISTS departments_name_key;
      ALTER TABLE departments DROP CONSTRAINT IF EXISTS departments_code_key;
      ALTER TABLE departments ADD CONSTRAINT departments_tenant_name_key UNIQUE (tenant_id, name);
      ALTER TABLE departments ADD CONSTRAINT departments_tenant_code_key UNIQUE (tenant_id, code);
      ALTER TABLE products    DROP CONSTRAINT IF EXISTS products_barcode_key;
      ALTER TABLE products    ADD CONSTRAINT products_tenant_barcode_key UNIQUE (tenant_id, barcode);
      ALTER TABLE sales       DROP CONSTRAINT IF EXISTS sales_receipt_number_key;
      ALTER TABLE sales       ADD CONSTRAINT sales_tenant_receipt_number_key UNIQUE (tenant_id, receipt_number);
      ALTER TABLE returns     DROP CONSTRAINT IF EXISTS returns_return_number_key;
      ALTER TABLE returns     ADD CONSTRAINT returns_tenant_return_number_key UNIQUE (tenant_id, return_number);
      ALTER TABLE settings    DROP CONSTRAINT IF EXISTS settings_pkey;
      ALTER TABLE settings    ADD CONSTRAINT settings_pkey PRIMARY KEY (tenant_id, key);
      ALTER TABLE sequences   DROP CONSTRAINT IF EXISTS sequences_pkey;
      ALTER TABLE sequences   ADD CONSTRAINT sequences_pkey PRIMARY KEY (tenant_id, name);

      CREATE INDEX IF NOT EXISTS idx_users_tenant           ON users(tenant_id);
      CREATE INDEX IF NOT EXISTS idx_sessions_tenant        ON sessions(tenant_id);
      CREATE INDEX IF NOT EXISTS idx_departments_tenant     ON departments(tenant_id);
      CREATE INDEX IF NOT EXISTS idx_products_tenant        ON products(tenant_id);
      CREATE INDEX IF NOT EXISTS idx_sales_tenant           ON sales(tenant_id, created_at DESC);
      CREATE INDEX IF NOT EXISTS idx_sale_items_tenant      ON sale_items(tenant_id);
      CREATE INDEX IF NOT EXISTS idx_returns_tenant         ON returns(tenant_id);
      CREATE INDEX IF NOT EXISTS idx_return_items_tenant    ON return_items(tenant_id);
      CREATE INDEX IF NOT EXISTS idx_stock_movements_tenant ON stock_movements(tenant_id, created_at DESC);

      -- ---- row-level security, forced, failing closed ----
      -- A transaction sees a row only if it declared that row's tenant.
      -- Declaring nothing yields zero rows — never everyone's rows.
      --
      -- The connection role (Supabase's "postgres") carries BYPASSRLS, which
      -- ignores every policy unconditionally — FORCE only binds owners. So
      -- tenant-scoped work runs as pos_app, a role without that attribute:
      -- lib/tenant.ts does SET LOCAL ROLE pos_app after BEGIN. Cross-tenant
      -- work (migrations, resolving a token, the platform admin) simply stays
      -- as the connection role, whose bypass is the intended behaviour there.
      CREATE OR REPLACE FUNCTION app_current_tenant() RETURNS BIGINT
        LANGUAGE sql STABLE AS $fn$
          SELECT NULLIF(current_setting('app.tenant_id', true), '')::BIGINT
        $fn$;

      DO $role$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pos_app') THEN
          CREATE ROLE pos_app NOLOGIN NOBYPASSRLS NOINHERIT;
        END IF;
      EXCEPTION WHEN duplicate_object THEN
        NULL; -- a parallel migration run created it first
      END
      $role$;
      GRANT pos_app TO CURRENT_USER;

      DO $grants$
      DECLARE sch TEXT := current_schema();
      BEGIN
        EXECUTE format('GRANT USAGE ON SCHEMA %I TO pos_app', sch);
        EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO pos_app', sch);
        EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO pos_app', sch);
        EXECUTE format('GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA %I TO pos_app', sch);
        EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO pos_app', sch);
        EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT USAGE, SELECT ON SEQUENCES TO pos_app', sch);
        EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT EXECUTE ON FUNCTIONS TO pos_app', sch);
      END
      $grants$;

      -- Every insert that omits tenant_id gets the tenant the transaction
      -- declared. Under a bypass nothing is declared, the default is NULL, and
      -- the NOT NULL constraint refuses the row — loudly, which is what an
      -- unscoped insert deserves. Services therefore never name tenant_id.
      DO $dd$
      DECLARE t TEXT;
      BEGIN
        FOREACH t IN ARRAY ARRAY[
          'users','sessions','departments','products','sales','sale_items',
          'returns','return_items','stock_movements','settings','sequences'
        ] LOOP
          EXECUTE format('ALTER TABLE %I ALTER COLUMN tenant_id SET DEFAULT app_current_tenant()', t);
        END LOOP;
      END
      $dd$;

      DO $do$
      DECLARE t TEXT;
      BEGIN
        FOREACH t IN ARRAY ARRAY[
          'users','sessions','departments','products','sales','sale_items',
          'returns','return_items','stock_movements','settings','sequences'
        ] LOOP
          EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
          EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
          EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I', t);
          EXECUTE format(
            'CREATE POLICY tenant_isolation ON %I
               USING      (tenant_id = app_current_tenant())
               WITH CHECK (tenant_id = app_current_tenant())', t);
        END LOOP;
      END
      $do$;

      -- Platform tables: RLS on with no policy. Only the connection role
      -- (which bypasses) can touch them — pos_app, and therefore any
      -- tenant-scoped request, is denied outright.
      ALTER TABLE tenants         ENABLE ROW LEVEL SECURITY;
      ALTER TABLE platform_admins ENABLE ROW LEVEL SECURITY;
      ALTER TABLE admin_sessions  ENABLE ROW LEVEL SECURITY;
      ALTER TABLE admin_actions   ENABLE ROW LEVEL SECURITY;

      -- The barcode cache is shared by every seller on purpose — a barcode is
      -- a barcode — so pos_app may read and write it freely.
      DROP POLICY IF EXISTS shared_cache ON barcode_lookups;
      CREATE POLICY shared_cache ON barcode_lookups USING (true) WITH CHECK (true);
    `,
  },
  {
    version: 10,
    name: 'canada_tax',
    sql: `
      -- Province-aware Canadian tax. GST/HST goes to the CRA and PST/QST/RST
      -- to the province, so a receipt keeps the two apart, and each product
      -- says which of them it attracts. Every new column on sales, sale_items
      -- and returns is a snapshot taken when the document was written: a
      -- later rate change must never rewrite an old receipt.
      ALTER TABLE products ADD COLUMN IF NOT EXISTS tax_class TEXT NOT NULL DEFAULT 'STANDARD';
      ALTER TABLE products DROP CONSTRAINT IF EXISTS products_tax_class_check;
      ALTER TABLE products ADD CONSTRAINT products_tax_class_check
        CHECK (tax_class IN ('STANDARD', 'GST_ONLY', 'EXEMPT'));

      -- NULL on receipts written before this migration: they used one flat rate.
      ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS tax_class TEXT;
      ALTER TABLE sales ADD COLUMN IF NOT EXISTS gst_cents    BIGINT;
      ALTER TABLE sales ADD COLUMN IF NOT EXISTS pst_cents    BIGINT;
      ALTER TABLE sales ADD COLUMN IF NOT EXISTS gst_rate_bps NUMERIC(8, 2);
      ALTER TABLE sales ADD COLUMN IF NOT EXISTS pst_rate_bps NUMERIC(8, 2); -- QST is 997.5 bps
      ALTER TABLE sales ADD COLUMN IF NOT EXISTS tax_hst      BOOLEAN;
      ALTER TABLE sales ADD COLUMN IF NOT EXISTS province     TEXT;
      ALTER TABLE sales ADD COLUMN IF NOT EXISTS gst_number   TEXT;
      ALTER TABLE sales ADD COLUMN IF NOT EXISTS pst_number   TEXT;

      -- Tax handed back by each refund, so the filing report can net it off.
      ALTER TABLE returns ADD COLUMN IF NOT EXISTS gst_cents BIGINT NOT NULL DEFAULT 0;
      ALTER TABLE returns ADD COLUMN IF NOT EXISTS pst_cents BIGINT NOT NULL DEFAULT 0;
    `,
  },
];

export const LATEST_SCHEMA_VERSION = migrations[migrations.length - 1].version;

const ADVISORY_LOCK_KEY = 7_303_291; // arbitrary constant shared by all server instances

export async function runMigrations(pool: Pool): Promise<void> {
  const client = await pool.connect();
  try {
    await client.query(`
      CREATE TABLE IF NOT EXISTS schema_migrations (
        version    INTEGER PRIMARY KEY,
        name       TEXT NOT NULL,
        applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
      )
    `);

    await client.query('SELECT pg_advisory_lock($1)', [ADVISORY_LOCK_KEY]);
    try {
      const applied = new Set(
        (await client.query<{ version: number }>('SELECT version FROM schema_migrations')).rows.map((r) =>
          Number(r.version),
        ),
      );

      for (const m of migrations) {
        if (applied.has(m.version)) continue;
        await client.query('BEGIN');
        try {
          // Runs as the connection role, which bypasses row-level security —
          // migrations must see every tenant's rows.
          await client.query(m.sql);
          await client.query('INSERT INTO schema_migrations (version, name) VALUES ($1, $2)', [m.version, m.name]);
          await client.query('COMMIT');
        } catch (err) {
          await client.query('ROLLBACK');
          throw new Error(`Migration ${m.version} (${m.name}) failed: ${(err as Error).message}`);
        }
        if (process.env.NODE_ENV !== 'test') {
          console.log(`[db] applied migration ${m.version}: ${m.name}`);
        }
      }
    } finally {
      await client.query('SELECT pg_advisory_unlock($1)', [ADVISORY_LOCK_KEY]);
    }
  } finally {
    client.release();
  }
}
