import type { Pool } from 'pg';

/**
 * Versioned, forward-only Postgres migrations, tracked in schema_migrations.
 * Each migration runs in its own transaction under an advisory lock so two
 * server instances starting together cannot both apply it. Never edit a
 * migration that has shipped; add a new one.
 *
 * Migration 1 recreates the layout the old supabase_schema.sql produced, so a
 * database that already has those tables passes through it untouched and is
 * then upgraded by 2..4 exactly like a fresh one.
 */
interface Migration {
  version: number;
  name: string;
  sql: string;
}

const migrations: Migration[] = [
  {
    version: 1,
    name: 'baseline',
    sql: `
      CREATE TABLE IF NOT EXISTS departments (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name        TEXT NOT NULL UNIQUE,
        code        TEXT NOT NULL UNIQUE,
        description TEXT,
        color       TEXT DEFAULT '#4f46e5',
        created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
      );

      CREATE TABLE IF NOT EXISTS products (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        barcode         TEXT NOT NULL UNIQUE,
        sku             TEXT,
        name            TEXT NOT NULL,
        department_id   BIGINT NOT NULL REFERENCES departments(id) ON DELETE RESTRICT,
        price           NUMERIC(10, 2) NOT NULL DEFAULT 0,
        cost_price      NUMERIC(10, 2) DEFAULT 0,
        stock_quantity  INTEGER NOT NULL DEFAULT 0,
        min_stock_level INTEGER NOT NULL DEFAULT 5,
        unit            TEXT DEFAULT 'pcs',
        image_url       TEXT,
        created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
      );

      CREATE TABLE IF NOT EXISTS sales (
        id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        receipt_number TEXT NOT NULL UNIQUE,
        subtotal       NUMERIC(10, 2) NOT NULL,
        tax_rate       NUMERIC(5, 2) DEFAULT 0,
        tax_amount     NUMERIC(10, 2) DEFAULT 0,
        discount       NUMERIC(10, 2) DEFAULT 0,
        total          NUMERIC(10, 2) NOT NULL,
        payment_method TEXT NOT NULL DEFAULT 'CASH',
        amount_paid    NUMERIC(10, 2) NOT NULL,
        change_due     NUMERIC(10, 2) DEFAULT 0,
        customer_name  TEXT DEFAULT 'Walk-in Customer',
        customer_phone TEXT,
        status         TEXT DEFAULT 'COMPLETED',
        created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
      );

      CREATE TABLE IF NOT EXISTS sale_items (
        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sale_id      BIGINT NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
        product_id   BIGINT REFERENCES products(id) ON DELETE SET NULL,
        product_name TEXT NOT NULL,
        barcode      TEXT NOT NULL,
        quantity     INTEGER NOT NULL,
        unit_price   NUMERIC(10, 2) NOT NULL,
        total_price  NUMERIC(10, 2) NOT NULL
      );

      CREATE TABLE IF NOT EXISTS stock_movements (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        product_id      BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
        type            TEXT NOT NULL,
        quantity_change INTEGER NOT NULL,
        quantity_before INTEGER NOT NULL,
        quantity_after  INTEGER NOT NULL,
        reference_id    TEXT,
        reason          TEXT,
        created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
      );

      ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS customer_name  TEXT;
      ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS customer_phone TEXT;
      ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS payment_method TEXT;
      ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS sale_id BIGINT REFERENCES sales(id) ON DELETE SET NULL;

      CREATE INDEX IF NOT EXISTS idx_products_barcode  ON products(barcode);
      CREATE INDEX IF NOT EXISTS idx_products_dept     ON products(department_id);
      CREATE INDEX IF NOT EXISTS idx_movements_prod    ON stock_movements(product_id);
      CREATE INDEX IF NOT EXISTS idx_movements_created ON stock_movements(created_at DESC);
      CREATE INDEX IF NOT EXISTS idx_sales_created     ON sales(created_at DESC);
    `,
  },
  {
    version: 2,
    name: 'money_in_integer_cents',
    sql: `
      -- The browser used to call this to check out; the Express server owns checkout now.
      DROP FUNCTION IF EXISTS process_pos_checkout;

      ALTER TABLE products
        ADD COLUMN IF NOT EXISTS price_cents      BIGINT NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS cost_price_cents BIGINT NOT NULL DEFAULT 0;
      UPDATE products SET
        price_cents      = ROUND(price * 100)::BIGINT,
        cost_price_cents = ROUND(COALESCE(cost_price, 0) * 100)::BIGINT;
      ALTER TABLE products DROP COLUMN IF EXISTS price, DROP COLUMN IF EXISTS cost_price;

      ALTER TABLE sales
        ADD COLUMN IF NOT EXISTS subtotal_cents    BIGINT NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS tax_rate_bps      INTEGER NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS tax_cents         BIGINT NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS discount_cents    BIGINT NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS total_cents       BIGINT NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS amount_paid_cents BIGINT NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS change_due_cents  BIGINT NOT NULL DEFAULT 0;
      UPDATE sales SET
        subtotal_cents    = ROUND(subtotal * 100)::BIGINT,
        tax_rate_bps      = ROUND(COALESCE(tax_rate, 0) * 100)::INTEGER,
        tax_cents         = ROUND(COALESCE(tax_amount, 0) * 100)::BIGINT,
        discount_cents    = ROUND(COALESCE(discount, 0) * 100)::BIGINT,
        total_cents       = ROUND(total * 100)::BIGINT,
        amount_paid_cents = ROUND(amount_paid * 100)::BIGINT,
        change_due_cents  = ROUND(COALESCE(change_due, 0) * 100)::BIGINT;
      ALTER TABLE sales
        DROP COLUMN IF EXISTS subtotal, DROP COLUMN IF EXISTS tax_rate, DROP COLUMN IF EXISTS tax_amount,
        DROP COLUMN IF EXISTS discount, DROP COLUMN IF EXISTS total, DROP COLUMN IF EXISTS amount_paid,
        DROP COLUMN IF EXISTS change_due;
      ALTER TABLE sales ALTER COLUMN status SET NOT NULL;

      ALTER TABLE sale_items
        ADD COLUMN IF NOT EXISTS unit_price_cents  BIGINT NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS total_price_cents BIGINT NOT NULL DEFAULT 0;
      UPDATE sale_items SET
        unit_price_cents  = ROUND(unit_price * 100)::BIGINT,
        total_price_cents = ROUND(total_price * 100)::BIGINT;
      ALTER TABLE sale_items DROP COLUMN IF EXISTS unit_price, DROP COLUMN IF EXISTS total_price;

      -- Receipts are history: refuse to delete a product that appears on one.
      ALTER TABLE sale_items DROP CONSTRAINT IF EXISTS sale_items_product_id_fkey;
      ALTER TABLE sale_items
        ADD CONSTRAINT sale_items_product_id_fkey
        FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT;

      CREATE INDEX IF NOT EXISTS idx_sale_items_sale ON sale_items(sale_id);
    `,
  },
  {
    version: 3,
    name: 'settings_and_sequences',
    sql: `
      CREATE TABLE IF NOT EXISTS settings (
        key        TEXT PRIMARY KEY,
        value      TEXT NOT NULL,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      INSERT INTO settings (key, value) VALUES
        ('store_name', 'Nexus POS'),
        ('currency', 'USD'),
        ('tax_rate_bps', '500')
      ON CONFLICT (key) DO NOTHING;

      CREATE TABLE IF NOT EXISTS sequences (
        name  TEXT PRIMARY KEY,
        value BIGINT NOT NULL DEFAULT 0
      );
    `,
  },
  {
    version: 4,
    name: 'lock_down_public_access',
    sql: `
      -- The old setup let the browser's anon key read and write every table.
      -- The Express server connects as the owner role, which bypasses RLS, so
      -- enabling RLS with no policies shuts the anon/authenticated roles out.
      ALTER TABLE departments     ENABLE ROW LEVEL SECURITY;
      ALTER TABLE products        ENABLE ROW LEVEL SECURITY;
      ALTER TABLE sales           ENABLE ROW LEVEL SECURITY;
      ALTER TABLE sale_items      ENABLE ROW LEVEL SECURITY;
      ALTER TABLE stock_movements ENABLE ROW LEVEL SECURITY;
      ALTER TABLE settings        ENABLE ROW LEVEL SECURITY;
      ALTER TABLE sequences       ENABLE ROW LEVEL SECURITY;

      DROP POLICY IF EXISTS "Allow public all access on departments"     ON departments;
      DROP POLICY IF EXISTS "Allow public all access on products"        ON products;
      DROP POLICY IF EXISTS "Allow public all access on sales"           ON sales;
      DROP POLICY IF EXISTS "Allow public all access on sale_items"      ON sale_items;
      DROP POLICY IF EXISTS "Allow public all access on stock_movements" ON stock_movements;

      -- Stop broadcasting table changes to anonymous realtime subscribers.
      DO $$
      DECLARE t TEXT;
      BEGIN
        IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
          FOR t IN
            SELECT tablename FROM pg_publication_tables
            WHERE pubname = 'supabase_realtime' AND schemaname = current_schema()
              AND tablename IN ('products', 'stock_movements', 'sales')
          LOOP
            EXECUTE format('ALTER PUBLICATION supabase_realtime DROP TABLE %I', t);
          END LOOP;
        END IF;
      END $$;
    `,
  },
  {
    version: 5,
    name: 'users_sessions_and_actors',
    sql: `
      CREATE TABLE IF NOT EXISTS users (
        id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username      TEXT NOT NULL UNIQUE,
        display_name  TEXT NOT NULL,
        password_hash TEXT NOT NULL,
        role          TEXT NOT NULL CHECK (role IN ('OWNER', 'MANAGER', 'CASHIER')),
        is_active     BOOLEAN NOT NULL DEFAULT true,
        created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
        last_login_at TIMESTAMPTZ
      );

      CREATE TABLE IF NOT EXISTS sessions (
        id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        token_hash TEXT NOT NULL UNIQUE,
        user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        expires_at TIMESTAMPTZ NOT NULL,
        revoked_at TIMESTAMPTZ,
        ip         TEXT
      );
      CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);

      -- Who did it: the cashier on every sale, the user on every stock movement.
      ALTER TABLE sales           ADD COLUMN IF NOT EXISTS cashier_id BIGINT REFERENCES users(id) ON DELETE SET NULL;
      ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS user_id    BIGINT REFERENCES users(id) ON DELETE SET NULL;

      ALTER TABLE users    ENABLE ROW LEVEL SECURITY;
      ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
    `,
  },
  {
    version: 6,
    name: 'returns_and_voids',
    sql: `
      CREATE TABLE IF NOT EXISTS returns (
        id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        return_number TEXT NOT NULL UNIQUE,
        sale_id       BIGINT NOT NULL REFERENCES sales(id) ON DELETE RESTRICT,
        kind          TEXT NOT NULL DEFAULT 'RETURN' CHECK (kind IN ('RETURN', 'VOID')),
        refund_cents  BIGINT NOT NULL,
        refund_method TEXT NOT NULL,
        reason        TEXT,
        processed_by  BIGINT REFERENCES users(id) ON DELETE SET NULL,
        created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE INDEX IF NOT EXISTS idx_returns_sale ON returns(sale_id);

      CREATE TABLE IF NOT EXISTS return_items (
        id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        return_id        BIGINT NOT NULL REFERENCES returns(id) ON DELETE CASCADE,
        sale_item_id     BIGINT NOT NULL REFERENCES sale_items(id) ON DELETE RESTRICT,
        product_id       BIGINT REFERENCES products(id) ON DELETE RESTRICT,
        product_name     TEXT NOT NULL,
        quantity         INTEGER NOT NULL CHECK (quantity > 0),
        unit_price_cents BIGINT NOT NULL,
        refund_cents     BIGINT NOT NULL,
        restock          BOOLEAN NOT NULL DEFAULT true,
        condition        TEXT
      );
      CREATE INDEX IF NOT EXISTS idx_return_items_sale_item ON return_items(sale_item_id);

      INSERT INTO settings (key, value) VALUES
        ('return_window_days', '30'),
        ('refund_approval_threshold_cents', '5000')
      ON CONFLICT (key) DO NOTHING;

      ALTER TABLE returns      ENABLE ROW LEVEL SECURITY;
      ALTER TABLE return_items ENABLE ROW LEVEL SECURITY;
    `,
  },
  {
    version: 7,
    name: 'barcode_lookup_cache',
    sql: `
      -- Answers from the external product registries, so a barcode is fetched
      -- once and never again. Misses are cached too, with a shorter life, so a
      -- shop full of unlisted stock does not re-query the registries on every scan.
      CREATE TABLE IF NOT EXISTS barcode_lookups (
        barcode      TEXT PRIMARY KEY,
        found        BOOLEAN NOT NULL,
        name         TEXT,
        brand        TEXT,
        unit         TEXT,
        category     TEXT,
        source       TEXT,
        looked_up_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE INDEX IF NOT EXISTS idx_barcode_lookups_looked_up ON barcode_lookups(looked_up_at);

      ALTER TABLE barcode_lookups ENABLE ROW LEVEL SECURITY;
    `,
  },
  {
    version: 8,
    name: 'archive_products',
    sql: `
      -- A product that has been sold can never be deleted: sale_items.product_id
      -- is ON DELETE RESTRICT, which is what stops a receipt line pointing at
      -- nothing. Archiving is the way to retire such a product — it leaves the
      -- catalogue and the register but keeps every receipt it appears on intact.
      -- Staff already work this way (users.is_active); products now match.
      ALTER TABLE products ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;

      -- Almost every read wants the active catalogue only.
      CREATE INDEX IF NOT EXISTS idx_products_active ON products(is_active) WHERE is_active;
    `,
  },
];

export const LATEST_SCHEMA_VERSION = migrations[migrations.length - 1].version;

const ADVISORY_LOCK_KEY = 7_303_291; // arbitrary constant shared by all server instances

export async function runMigrations(pool: Pool): Promise<void> {
  const client = await pool.connect();
  try {
    await client.query(`
      CREATE TABLE IF NOT EXISTS schema_migrations (
        version    INTEGER PRIMARY KEY,
        name       TEXT NOT NULL,
        applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
      )
    `);

    await client.query('SELECT pg_advisory_lock($1)', [ADVISORY_LOCK_KEY]);
    try {
      const applied = new Set(
        (await client.query<{ version: number }>('SELECT version FROM schema_migrations')).rows.map((r) =>
          Number(r.version),
        ),
      );

      for (const m of migrations) {
        if (applied.has(m.version)) continue;
        await client.query('BEGIN');
        try {
          await client.query(m.sql);
          await client.query('INSERT INTO schema_migrations (version, name) VALUES ($1, $2)', [m.version, m.name]);
          await client.query('COMMIT');
        } catch (err) {
          await client.query('ROLLBACK');
          throw new Error(`Migration ${m.version} (${m.name}) failed: ${(err as Error).message}`);
        }
        if (process.env.NODE_ENV !== 'test') {
          console.log(`[db] applied migration ${m.version}: ${m.name}`);
        }
      }
    } finally {
      await client.query('SELECT pg_advisory_unlock($1)', [ADVISORY_LOCK_KEY]);
    }
  } finally {
    client.release();
  }
}
