import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { getPool } from '../db';
import { LATEST_SCHEMA_VERSION, runMigrations } from '../migrations';
import { createTestSchema, dropTestSchema, hasDatabase } from './helpers';

/**
 * Recreates, inside this file's private schema, exactly what the old
 * supabase_schema.sql produced on the live project: NUMERIC money columns,
 * wide-open RLS policies and the client-side checkout function. Then proves
 * the migrations upgrade it losslessly and close the public access.
 */
async function createLegacyLayout(): Promise<void> {
  await getPool().query(`
    CREATE TABLE departments (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL UNIQUE, code TEXT NOT NULL UNIQUE,
      description TEXT, color TEXT DEFAULT '#4f46e5', created_at TIMESTAMPTZ DEFAULT now() NOT NULL
    );
    CREATE TABLE products (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, barcode TEXT NOT NULL UNIQUE, sku TEXT, name TEXT NOT NULL,
      department_id BIGINT NOT NULL REFERENCES departments(id) ON DELETE RESTRICT,
      price NUMERIC(10, 2) NOT NULL DEFAULT 0.00, cost_price NUMERIC(10, 2) DEFAULT 0.00,
      stock_quantity INTEGER NOT NULL DEFAULT 0, min_stock_level INTEGER NOT NULL DEFAULT 5, unit TEXT DEFAULT 'pcs',
      image_url TEXT, created_at TIMESTAMPTZ DEFAULT now() NOT NULL, updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
    );
    CREATE TABLE sales (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, receipt_number TEXT NOT NULL UNIQUE,
      subtotal NUMERIC(10, 2) NOT NULL, tax_rate NUMERIC(5, 2) DEFAULT 0.00, tax_amount NUMERIC(10, 2) DEFAULT 0.00,
      discount NUMERIC(10, 2) DEFAULT 0.00, total NUMERIC(10, 2) NOT NULL, payment_method TEXT NOT NULL DEFAULT 'CASH',
      amount_paid NUMERIC(10, 2) NOT NULL, change_due NUMERIC(10, 2) DEFAULT 0.00,
      customer_name TEXT DEFAULT 'Walk-in Customer', customer_phone TEXT, status TEXT DEFAULT 'COMPLETED',
      created_at TIMESTAMPTZ DEFAULT now() NOT NULL
    );
    CREATE TABLE sale_items (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sale_id BIGINT NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
      product_id BIGINT REFERENCES products(id) ON DELETE SET NULL, product_name TEXT NOT NULL, barcode TEXT NOT NULL,
      quantity INTEGER NOT NULL, unit_price NUMERIC(10, 2) NOT NULL, total_price NUMERIC(10, 2) NOT NULL
    );
    CREATE TABLE stock_movements (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
      type TEXT NOT NULL, quantity_change INTEGER NOT NULL, quantity_before INTEGER NOT NULL, quantity_after INTEGER NOT NULL,
      reference_id TEXT, reason TEXT, customer_name TEXT, customer_phone TEXT, payment_method TEXT,
      sale_id BIGINT REFERENCES sales(id) ON DELETE SET NULL, created_at TIMESTAMPTZ DEFAULT now() NOT NULL
    );
    ALTER TABLE departments ENABLE ROW LEVEL SECURITY;
    ALTER TABLE products ENABLE ROW LEVEL SECURITY;
    CREATE POLICY "Allow public all access on departments" ON departments FOR ALL USING (true) WITH CHECK (true);
    CREATE POLICY "Allow public all access on products" ON products FOR ALL USING (true) WITH CHECK (true);
    CREATE FUNCTION process_pos_checkout(p_items JSONB) RETURNS JSONB LANGUAGE sql AS 'SELECT $1';

    INSERT INTO departments (name, code) VALUES ('Beverages', 'BEV');
    INSERT INTO products (barcode, name, department_id, price, cost_price, stock_quantity)
      VALUES ('111', 'Oats', 1, 4.35, 2.1, 7), ('222', 'Juice', 1, 12.99, NULL, 3);
    INSERT INTO sales (receipt_number, subtotal, tax_rate, tax_amount, discount, total, payment_method, amount_paid, change_due)
      VALUES ('REC-OLD-1', 5.97, 5, 0.3, 0, 6.27, 'CASH', 10, 3.73);
    INSERT INTO sale_items (sale_id, product_id, product_name, barcode, quantity, unit_price, total_price)
      VALUES (1, 1, 'Oats', '111', 3, 1.99, 5.97);
    INSERT INTO stock_movements (product_id, type, quantity_change, quantity_before, quantity_after)
      VALUES (1, 'INITIAL', 7, 0, 7);
  `);
}

const columns = async (table: string) =>
  (
    await getPool().query<{ column_name: string }>(
      'SELECT column_name FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = $1',
      [table],
    )
  ).rows.map((r) => r.column_name);

const versions = async () =>
  (await getPool().query<{ version: number }>('SELECT version FROM schema_migrations ORDER BY version')).rows.map(
    (r) => r.version,
  );

// Every test file runs migrations under one global advisory lock, so when the
// whole suite runs in parallel this file can wait on the others. Allow for it.
describe.skipIf(!hasDatabase)('migrations', { timeout: 120_000 }, () => {
  beforeAll(() => createTestSchema(false));
  afterAll(dropTestSchema);

  it('upgrades the legacy Supabase layout to integer cents and closes public access', async () => {
    await createLegacyLayout();
    await runMigrations(getPool());

    expect(await versions()).toEqual(Array.from({ length: LATEST_SCHEMA_VERSION }, (_, i) => i + 1));

    const products = await getPool().query(
      'SELECT barcode, price_cents, cost_price_cents, stock_quantity FROM products ORDER BY id',
    );
    expect(products.rows).toEqual([
      { barcode: '111', price_cents: 435, cost_price_cents: 210, stock_quantity: 7 },
      { barcode: '222', price_cents: 1299, cost_price_cents: 0, stock_quantity: 3 },
    ]);
    expect(await columns('products')).not.toContain('price');

    const sale = await getPool().query(
      'SELECT receipt_number, subtotal_cents, tax_rate_bps, tax_cents, discount_cents, total_cents, amount_paid_cents, change_due_cents FROM sales',
    );
    expect(sale.rows[0]).toEqual({
      receipt_number: 'REC-OLD-1',
      subtotal_cents: 597,
      tax_rate_bps: 500,
      tax_cents: 30,
      discount_cents: 0,
      total_cents: 627,
      amount_paid_cents: 1000,
      change_due_cents: 373,
    });
    expect(await columns('sales')).not.toContain('total');

    const item = await getPool().query('SELECT unit_price_cents, total_price_cents FROM sale_items');
    expect(item.rows[0]).toEqual({ unit_price_cents: 199, total_price_cents: 597 });

    // Sold products can no longer be deleted out from under their receipts.
    await expect(getPool().query('DELETE FROM products WHERE barcode = $1', ['111'])).rejects.toMatchObject({
      code: '23503',
    });

    // The wide-open policies and the client-side checkout RPC are gone.
    const policies = await getPool().query(
      'SELECT policyname FROM pg_policies WHERE schemaname = current_schema()',
    );
    expect(policies.rows).toEqual([]);
    const fn = await getPool().query(
      "SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace WHERE p.proname = 'process_pos_checkout' AND n.nspname = current_schema()",
    );
    expect(fn.rows).toEqual([]);

    const rls = await getPool().query(
      "SELECT relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = current_schema() AND c.relkind = 'r' AND c.relrowsecurity ORDER BY relname",
    );
    expect(rls.rows.map((r) => r.relname)).toEqual([
      'departments', 'products', 'return_items', 'returns', 'sale_items', 'sales', 'sequences', 'sessions', 'settings',
      'stock_movements', 'users',
    ]);

    // Actor columns exist and are nullable so legacy rows survive.
    expect(await columns('sales')).toContain('cashier_id');
    expect(await columns('stock_movements')).toContain('user_id');

    const settings = await getPool().query("SELECT value FROM settings WHERE key = 'tax_rate_bps'");
    expect(settings.rows[0]).toEqual({ value: '500' });
  });

  it('is idempotent', async () => {
    const before = (await getPool().query('SELECT * FROM products ORDER BY id')).rows;
    await runMigrations(getPool());
    expect(await versions()).toHaveLength(LATEST_SCHEMA_VERSION);
    expect((await getPool().query('SELECT * FROM products ORDER BY id')).rows).toEqual(before);
  });
});
